import HautevilleHouse.DynamicsPhaseBoundariesSolidsLemmaCanonicalLaneLean.PhaseFieldCahnHilliard
import HautevilleHouse.DynamicsPhaseBoundariesSolidsLemmaCanonicalLaneLean.SharpInterfaceAllenCahn
import HautevilleHouse.DynamicsPhaseBoundariesSolidsLemmaCanonicalLaneLean.SharpInterfaceStefanProblem
import HautevilleHouse.DynamicsPhaseBoundariesSolidsLemmaCanonicalLaneLean.MullinsSekerkaInstability
import HautevilleHouse.DynamicsPhaseBoundariesSolidsLemmaCanonicalLaneLean.PhaseFieldCrystalDensity

-- Root module for DynamicsPhaseBoundariesSolidsLemmaCanonicalLaneLean
namespace HautevilleHouse
namespace DynamicsPhaseBoundariesSolidsLemmaCanonicalLaneLean

theorem all_packages_imported : Prop := True

end DynamicsPhaseBoundariesSolidsLemmaCanonicalLaneLean
end HautevilleHouse